name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 12 */4 * *" # Kör kl 12:00 var 4:e dag
  workflow_dispatch: # Möjlighet att köra manuellt

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -s -X GET "https://${{ secrets.DEV_NEXT_PUBLIC_SUPABASE_URL }}.supabase.co/Clients?select=*" \
          -H "apikey: ${{ secrets.DEV_NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
